# Generated by Django 4.2.5 on 2023-09-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_taskmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
