# Generated by Django 4.2.5 on 2023-09-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_taskmodel_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='priority_slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
